name: Windows Artifacts

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  windows-msys:
    name: Windows MSYS2
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - uses: actions/checkout@v4
      - uses: msys2/setup-msys2@v2
        with:
          msystem: UCRT64
          update: true
          install: git make zip mingw-w64-ucrt-x86_64-gcc mingw-w64-ucrt-x86_64-dlfcn
      - name: Build
        run: |
           make -j$(getconf _NPROCESSORS_ONLN) CONFIG_WERROR=y
      - name: Stats
        run: |
          ./qjs -qd
      - name: Run built-in tests
        run: |
          make test
      - name: Run microbench
        run: |
          make microbench
      - name: Package Artifacts
        run: |
          zip -r quickjs-windows-msys2.zip qjs.exe qjsc.exe
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: quickjs-windows-msys2.zip
          path: quickjs-windows-msys2.zip
